config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/books')

  resources :books do
    member do
      get :delete
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(:id)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(books_path, notice: "Book created")
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to(book_path(@book), notice: "Book saved")
    else
      render('new')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to(books_path, notice: "Book deleted")
  end

  def book_params
    params.require(:book).permit(
      :title
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<table summary="Task form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
</table>

app/views/books/delete.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books delete">
  <h2>Delete Book?</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit Book</h2>

  <%= form_for(@book) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Save Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<% flash.each do |type, msg| %>
  <div class="flash-notice"><%= msg %></div>
<% end %>

<div class="books index">
  <h2>Books</h2>

  <%= link_to("Add New Book", new_book_path, class: 'action new') %>

  <table class="listing" summary="Book list" style="width: 100%;">
    <tr class="header">
      <th>Book</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<% flash.each do |type, msg| %>
  <div class="flash-notice"><%= msg %></div>
<% end %>

<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books show">
  <h2>Show book</h2>

  <p>Title: <%= @book.title %></p>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete', delete_book_path(@book)) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>